// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/category"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type CategoryServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedCategoryServer
}

func NewCategoryServer(svcCtx *svc.ServiceContext) *CategoryServer {
	return &CategoryServer{
		svcCtx: svcCtx,
	}
}

func (s *CategoryServer) InsertCategory(ctx context.Context, in *admin.CategoryReq) (*admin.AffectedResp, error) {
	l := categorylogic.NewInsertCategoryLogic(ctx, s.svcCtx)
	return l.InsertCategory(in)
}

func (s *CategoryServer) UpdateCategory(ctx context.Context, in *admin.CategoryReq) (*admin.AffectedResp, error) {
	l := categorylogic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *CategoryServer) UpdateStatus(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := categorylogic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}

func (s *CategoryServer) RemoveCategory(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := categorylogic.NewRemoveCategoryLogic(ctx, s.svcCtx)
	return l.RemoveCategory(in)
}

func (s *CategoryServer) GetCategory(ctx context.Context, in *admin.Id) (*admin.CategoryUnit, error) {
	l := categorylogic.NewGetCategoryLogic(ctx, s.svcCtx)
	return l.GetCategory(in)
}

func (s *CategoryServer) GetList(ctx context.Context, in *admin.Empty) (*admin.ListCategoryResp, error) {
	l := categorylogic.NewGetListLogic(ctx, s.svcCtx)
	return l.GetList(in)
}

func (s *CategoryServer) GetListByParent(ctx context.Context, in *admin.Id) (*admin.ListCategoryResp, error) {
	l := categorylogic.NewGetListByParentLogic(ctx, s.svcCtx)
	return l.GetListByParent(in)
}

func (s *CategoryServer) GetListByClass(ctx context.Context, in *admin.ClassReq) (*admin.ListCategoryResp, error) {
	l := categorylogic.NewGetListByClassLogic(ctx, s.svcCtx)
	return l.GetListByClass(in)
}
