// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package role

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	BatchIdsReq       = admin.BatchIdsReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Role interface {
		InsertRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateStatus(ctx context.Context, in *UuidStatusReq, opts ...grpc.CallOption) (*AffectedResp, error)
		RemoveRole(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*AffectedResp, error)
		GetRole(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*RoleUnit, error)
		ListRole(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListRoleResp, error)
		GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoleListResp, error)
	}

	defaultRole struct {
		cli zrpc.Client
	}
)

func NewRole(cli zrpc.Client) Role {
	return &defaultRole{
		cli: cli,
	}
}

func (m *defaultRole) InsertRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.InsertRole(ctx, in, opts...)
}

func (m *defaultRole) UpdateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultRole) UpdateStatus(ctx context.Context, in *UuidStatusReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}

func (m *defaultRole) RemoveRole(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.RemoveRole(ctx, in, opts...)
}

func (m *defaultRole) GetRole(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*RoleUnit, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.GetRole(ctx, in, opts...)
}

func (m *defaultRole) ListRole(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListRoleResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.ListRole(ctx, in, opts...)
}

func (m *defaultRole) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := admin.NewRoleClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}
