// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/media"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type MediaServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedMediaServer
}

func NewMediaServer(svcCtx *svc.ServiceContext) *MediaServer {
	return &MediaServer{
		svcCtx: svcCtx,
	}
}

func (s *MediaServer) InsertMedia(ctx context.Context, in *admin.MediaReq) (*admin.AffectedResp, error) {
	l := medialogic.NewInsertMediaLogic(ctx, s.svcCtx)
	return l.InsertMedia(in)
}

func (s *MediaServer) UpdateMedia(ctx context.Context, in *admin.MediaReq) (*admin.AffectedResp, error) {
	l := medialogic.NewUpdateMediaLogic(ctx, s.svcCtx)
	return l.UpdateMedia(in)
}

func (s *MediaServer) UpdateMediaTitle(ctx context.Context, in *admin.MediaTitleReq) (*admin.AffectedResp, error) {
	l := medialogic.NewUpdateMediaTitleLogic(ctx, s.svcCtx)
	return l.UpdateMediaTitle(in)
}

func (s *MediaServer) GetMedia(ctx context.Context, in *admin.Id) (*admin.MediaUnit, error) {
	l := medialogic.NewGetMediaLogic(ctx, s.svcCtx)
	return l.GetMedia(in)
}

func (s *MediaServer) RemoveMedia(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := medialogic.NewRemoveMediaLogic(ctx, s.svcCtx)
	return l.RemoveMedia(in)
}

func (s *MediaServer) ListMedia(ctx context.Context, in *admin.PageReq) (*admin.ListMediaResp, error) {
	l := medialogic.NewListMediaLogic(ctx, s.svcCtx)
	return l.ListMedia(in)
}
