// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package userrole

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	BatchIdsReq       = admin.BatchIdsReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	UserRole interface {
		InsertUserRole(ctx context.Context, in *UserRoleReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*AffectedResp, error)
		RemoveUserRole(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		GetUserRoles(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*UserRoleListResp, error)
	}

	defaultUserRole struct {
		cli zrpc.Client
	}
)

func NewUserRole(cli zrpc.Client) UserRole {
	return &defaultUserRole{
		cli: cli,
	}
}

func (m *defaultUserRole) InsertUserRole(ctx context.Context, in *UserRoleReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewUserRoleClient(m.cli.Conn())
	return client.InsertUserRole(ctx, in, opts...)
}

func (m *defaultUserRole) UpdateUserRole(ctx context.Context, in *UpdateUserRoleReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewUserRoleClient(m.cli.Conn())
	return client.UpdateUserRole(ctx, in, opts...)
}

func (m *defaultUserRole) RemoveUserRole(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewUserRoleClient(m.cli.Conn())
	return client.RemoveUserRole(ctx, in, opts...)
}

func (m *defaultUserRole) GetUserRoles(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*UserRoleListResp, error) {
	client := admin.NewUserRoleClient(m.cli.Conn())
	return client.GetUserRoles(ctx, in, opts...)
}
