// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package article

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	ArticleCategory   = admin.ArticleCategory
	ArticleDataUnit   = admin.ArticleDataUnit
	ArticleUnit       = admin.ArticleUnit
	BatchIdsReq       = admin.BatchIdsReq
	CategoryReq       = admin.CategoryReq
	CategoryUnit      = admin.CategoryUnit
	ClassReq          = admin.ClassReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListArticleResp   = admin.ListArticleResp
	ListCategoryResp  = admin.ListCategoryResp
	ListMediaResp     = admin.ListMediaResp
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MediaReq          = admin.MediaReq
	MediaTitleReq     = admin.MediaTitleReq
	MediaUnit         = admin.MediaUnit
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Article interface {
		InsertArticle(ctx context.Context, in *ArticleUnit, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateArticle(ctx context.Context, in *ArticleUnit, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*AffectedResp, error)
		RemoveArticle(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		GetArticle(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ArticleUnit, error)
		ListArticle(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListArticleResp, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) InsertArticle(ctx context.Context, in *ArticleUnit, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.InsertArticle(ctx, in, opts...)
}

func (m *defaultArticle) UpdateArticle(ctx context.Context, in *ArticleUnit, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.UpdateArticle(ctx, in, opts...)
}

func (m *defaultArticle) UpdateStatus(ctx context.Context, in *StatusReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}

func (m *defaultArticle) RemoveArticle(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.RemoveArticle(ctx, in, opts...)
}

func (m *defaultArticle) GetArticle(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ArticleUnit, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.GetArticle(ctx, in, opts...)
}

func (m *defaultArticle) ListArticle(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListArticleResp, error) {
	client := admin.NewArticleClient(m.cli.Conn())
	return client.ListArticle(ctx, in, opts...)
}
