// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package media

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	BatchIdsReq       = admin.BatchIdsReq
	CategoryReq       = admin.CategoryReq
	CategoryUnit      = admin.CategoryUnit
	ClassReq          = admin.ClassReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListCategoryResp  = admin.ListCategoryResp
	ListMediaResp     = admin.ListMediaResp
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MediaReq          = admin.MediaReq
	MediaTitleReq     = admin.MediaTitleReq
	MediaUnit         = admin.MediaUnit
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Media interface {
		InsertMedia(ctx context.Context, in *MediaReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateMedia(ctx context.Context, in *MediaReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateMediaTitle(ctx context.Context, in *MediaTitleReq, opts ...grpc.CallOption) (*AffectedResp, error)
		GetMedia(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MediaUnit, error)
		RemoveMedia(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		ListMedia(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListMediaResp, error)
	}

	defaultMedia struct {
		cli zrpc.Client
	}
)

func NewMedia(cli zrpc.Client) Media {
	return &defaultMedia{
		cli: cli,
	}
}

func (m *defaultMedia) InsertMedia(ctx context.Context, in *MediaReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.InsertMedia(ctx, in, opts...)
}

func (m *defaultMedia) UpdateMedia(ctx context.Context, in *MediaReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.UpdateMedia(ctx, in, opts...)
}

func (m *defaultMedia) UpdateMediaTitle(ctx context.Context, in *MediaTitleReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.UpdateMediaTitle(ctx, in, opts...)
}

func (m *defaultMedia) GetMedia(ctx context.Context, in *Id, opts ...grpc.CallOption) (*MediaUnit, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.GetMedia(ctx, in, opts...)
}

func (m *defaultMedia) RemoveMedia(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.RemoveMedia(ctx, in, opts...)
}

func (m *defaultMedia) ListMedia(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListMediaResp, error) {
	client := admin.NewMediaClient(m.cli.Conn())
	return client.ListMedia(ctx, in, opts...)
}
