// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package category

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	ArticleCategory   = admin.ArticleCategory
	ArticleDataUnit   = admin.ArticleDataUnit
	ArticleUnit       = admin.ArticleUnit
	BatchIdsReq       = admin.BatchIdsReq
	CategoryReq       = admin.CategoryReq
	CategoryUnit      = admin.CategoryUnit
	ClassReq          = admin.ClassReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListArticleResp   = admin.ListArticleResp
	ListCategoryResp  = admin.ListCategoryResp
	ListMediaResp     = admin.ListMediaResp
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MediaReq          = admin.MediaReq
	MediaTitleReq     = admin.MediaTitleReq
	MediaUnit         = admin.MediaUnit
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Category interface {
		InsertCategory(ctx context.Context, in *CategoryReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateCategory(ctx context.Context, in *CategoryReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateStatus(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		RemoveCategory(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		GetCategory(ctx context.Context, in *Id, opts ...grpc.CallOption) (*CategoryUnit, error)
		GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoryResp, error)
		GetListByParent(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListCategoryResp, error)
		GetListByClass(ctx context.Context, in *ClassReq, opts ...grpc.CallOption) (*ListCategoryResp, error)
	}

	defaultCategory struct {
		cli zrpc.Client
	}
)

func NewCategory(cli zrpc.Client) Category {
	return &defaultCategory{
		cli: cli,
	}
}

func (m *defaultCategory) InsertCategory(ctx context.Context, in *CategoryReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.InsertCategory(ctx, in, opts...)
}

func (m *defaultCategory) UpdateCategory(ctx context.Context, in *CategoryReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultCategory) UpdateStatus(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}

func (m *defaultCategory) RemoveCategory(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.RemoveCategory(ctx, in, opts...)
}

func (m *defaultCategory) GetCategory(ctx context.Context, in *Id, opts ...grpc.CallOption) (*CategoryUnit, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.GetCategory(ctx, in, opts...)
}

func (m *defaultCategory) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListCategoryResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultCategory) GetListByParent(ctx context.Context, in *Id, opts ...grpc.CallOption) (*ListCategoryResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.GetListByParent(ctx, in, opts...)
}

func (m *defaultCategory) GetListByClass(ctx context.Context, in *ClassReq, opts ...grpc.CallOption) (*ListCategoryResp, error) {
	client := admin.NewCategoryClient(m.cli.Conn())
	return client.GetListByClass(ctx, in, opts...)
}
