// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/account"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Login(ctx context.Context, in *admin.LoginReq) (*admin.LoginResp, error) {
	l := accountlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AccountServer) Register(ctx context.Context, in *admin.RegisterReq) (*admin.AffectedResp, error) {
	l := accountlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AccountServer) RefreshToken(ctx context.Context, in *admin.TokenReq) (*admin.TokenResp, error) {
	l := accountlogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

func (s *AccountServer) SetPassword(ctx context.Context, in *admin.PasswordReq) (*admin.AffectedResp, error) {
	l := accountlogic.NewSetPasswordLogic(ctx, s.svcCtx)
	return l.SetPassword(in)
}

func (s *AccountServer) GetPermission(ctx context.Context, in *admin.Uuid) (*admin.PermissionResp, error) {
	l := accountlogic.NewGetPermissionLogic(ctx, s.svcCtx)
	return l.GetPermission(in)
}
