// Code generated by goctl. DO NOT EDIT!

package model

import (
	"bodhiadmin/common/utils"
	"context"
	"github.com/SpectatorNan/gorm-zero/gormc"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
	"strings"
)

var ()

type (
	articleModel interface {
		Insert(ctx context.Context, data *Article) error
		FindOne(ctx context.Context, id int64, preload bool) (*Article, error)
		FindOneBySlug(ctx context.Context, slug string) (*Article, error)
		Update(ctx context.Context, data *Article) error
		Delete(ctx context.Context, id int64) error

		UpdateStatus(ctx context.Context, id int64, column string) error
		FindListByPage(ctx context.Context, req PageReq) ([]*Article, int64, error)
		InsertWithRelationData(ctx context.Context, data *Article, categoryIds []int64) error
		UpdateArticle(ctx context.Context, id int64, data map[string]interface{}) error
	}

	defaultArticleModel struct {
		conn  *gorm.DB
		table string
	}

	Article struct {
		Id        int64                 `gorm:"column:id;primaryKey;"`
		CoverImg  string                `gorm:"column:cover_img"`          // 封面
		Slug      string                `gorm:"column:slug;unique"`        // slug
		Title     string                `gorm:"column:title"`              // 名称
		Author    string                `gorm:"column:author"`             // 作者
		Content   string                `gorm:"column:content"`            // 内容
		Pv        int64                 `gorm:"column:pv"`                 // 访问量
		IsCommend int64                 `gorm:"default:0"`                 // 是否推荐 0不推荐 1推荐
		IsTop     int64                 `gorm:"default:0"`                 // 是否置顶 0正常 1置顶
		IsEnabled int64                 `gorm:"default:1"`                 // 是否有效 0无效 1有效
		IsDeleted soft_delete.DeletedAt `gorm:"softDelete:flag,default:0"` // 是否删除
		CreatedAt int64                 `gorm:"<-:create;autoCreateTime"`
		UpdatedAt int64                 `gorm:"<-;autoUpdateTime"` // 更新时间

		CategoryLinks []ArticleCategoryLink `gorm:"foreignKey:ArticleId;references:Id"`
		Categories    []Category            `gorm:"many2many:article_category;joinForeignKey:ArticleId;joinReferences:CategoryId"`
	}
)

func (Article) TableName() string {
	return "`article`"
}

func newArticleModel(conn *gorm.DB) *defaultArticleModel {
	return &defaultArticleModel{
		conn:  conn,
		table: "`article`",
	}
}

func (m *defaultArticleModel) Insert(ctx context.Context, data *Article) error {
	err := m.conn.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultArticleModel) FindOneBySlug(ctx context.Context, slug string) (*Article, error) {
	var resp Article
	db := m.conn.WithContext(ctx).Model(&Article{})
	db.Where("`slug` = ?", slug)
	db.Preload("CategoryLinks")
	err := db.Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleModel) FindOne(ctx context.Context, id int64, preload bool) (*Article, error) {
	var resp Article
	db := m.conn.WithContext(ctx).Model(&Article{})
	db.Where("`id` = ?", id)
	if preload {
		db.Preload("CategoryLinks")
	}
	err := db.Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleModel) InsertWithRelationData(ctx context.Context, data *Article, categoryIds []int64) error {

	for _, cid := range categoryIds {
		data.CategoryLinks = append(data.CategoryLinks, ArticleCategoryLink{
			CategoryId: cid,
		})
	}

	//fmt.Println("insert data ++++ ", data)
	db := m.conn.WithContext(ctx).Model(Article{})
	err := db.Create(&data).Error
	if err != nil {
		return err
	}
	err = db.Where("id = ?", data.Id).Save(&data).Error
	return err
}
func (m *defaultArticleModel) UpdateArticle(ctx context.Context, id int64, data map[string]interface{}) error {
	db := m.conn.WithContext(ctx).Model(Article{})
	db.Where("`id` = ?", id)
	err := db.Updates(&data).Error
	if err != nil {
		return err
	}
	return err
}

func (m *defaultArticleModel) UpdateStatus(ctx context.Context, id int64, column string) error {
	old, err := m.FindOne(ctx, id, false)
	if err != nil {
		return err
	}
	data := 0
	if (column == "IsEnabled" && old.IsEnabled == 0) || (column == "IsTop" && old.IsTop == 0) || (column == "IsCommend" && old.IsCommend == 0) {
		data = 1
	}
	err = m.conn.Model(&Article{}).Where("id = ?", id).Update(column, data).Error
	return err
}

func (m *defaultArticleModel) FindListByPage(ctx context.Context, req PageReq) ([]*Article, int64, error) {
	var list []*Article
	var total int64

	sortBy := utils.GetSortByStr(req.Sort, req.Order, Article{})
	db := m.conn.WithContext(ctx).Model(Article{})
	value := strings.TrimSpace(req.Value)
	if len(value) != 0 {
		key := "%" + value + "%"
		db.Where("`title` LIKE ? OR `author` LIKE ? ", key, key)
	}
	db.Count(&total)
	db.Preload("Categories")
	db.Scopes(utils.Paginate(req.Page, req.Size))
	db.Order(sortBy)
	err := db.Find(&list).Error
	if err != nil {
		return nil, 0, err
	}
	return list, total, nil
}

func (m *defaultArticleModel) Update(ctx context.Context, data *Article) error {
	err := m.conn.WithContext(ctx).Omit("is_enabled").Save(data).Error
	return err
}

func (m *defaultArticleModel) Delete(ctx context.Context, id int64) error {
	err := m.conn.WithContext(ctx).Delete(&Article{}, id).Error

	return err
}

func (m *defaultArticleModel) tableName() string {
	return m.table
}
