// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"github.com/SpectatorNan/gorm-zero/gormc"
	"gorm.io/gorm"
)

var ()

type (
	articleCategoryLinkModel interface {
		Insert(ctx context.Context, data *ArticleCategoryLink) error
		FindOne(ctx context.Context, id int64) (*ArticleCategoryLink, error)
		Update(ctx context.Context, data *ArticleCategoryLink) error
		Delete(ctx context.Context, id int64) error
	}

	defaultArticleCategoryLinkModel struct {
		conn  *gorm.DB
		table string
	}

	ArticleCategoryLink struct {
		Id         int64 `gorm:"column:id"`
		ArticleId  int64 `gorm:"column:article_id"`  // article id
		CategoryId int64 `gorm:"column:category_id"` // category id
	}
)

func (ArticleCategoryLink) TableName() string {
	return "`article_category_link`"
}

func newArticleCategoryLinkModel(conn *gorm.DB) *defaultArticleCategoryLinkModel {
	return &defaultArticleCategoryLinkModel{
		conn:  conn,
		table: "`article_category_link`",
	}
}

func (m *defaultArticleCategoryLinkModel) Insert(ctx context.Context, data *ArticleCategoryLink) error {
	err := m.conn.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultArticleCategoryLinkModel) FindOne(ctx context.Context, id int64) (*ArticleCategoryLink, error) {
	var resp ArticleCategoryLink
	err := m.conn.WithContext(ctx).Model(&ArticleCategoryLink{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultArticleCategoryLinkModel) Update(ctx context.Context, data *ArticleCategoryLink) error {
	err := m.conn.WithContext(ctx).Save(data).Error
	return err
}

func (m *defaultArticleCategoryLinkModel) Delete(ctx context.Context, id int64) error {
	err := m.conn.WithContext(ctx).Delete(&ArticleCategoryLink{}, id).Error

	return err
}

func (m *defaultArticleCategoryLinkModel) tableName() string {
	return m.table
}
