// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"github.com/SpectatorNan/gorm-zero/gormc"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
)

var ()

type (
	categoryModel interface {
		Insert(ctx context.Context, data *Category) error
		FindOne(ctx context.Context, id int64) (*Category, error)
		//FindOneByClass(ctx context.Context, class string) (*Category, error)
		Update(ctx context.Context, data *Category) error
		Delete(ctx context.Context, id int64) error

		FindAll(ctx context.Context) ([]*Category, error)
		FindListByClass(ctx context.Context, class string) ([]*Category, error)
		FindListByPid(ctx context.Context, pid int64) ([]*Category, error)
		UpdateStatus(ctx context.Context, id int64) error
	}

	defaultCategoryModel struct {
		conn  *gorm.DB
		table string
	}

	Category struct {
		Id        int64                 `gorm:"column:id"`
		ParentId  int64                 `gorm:"column:parent_id"`          // 父id
		Title     string                `gorm:"column:title"`              // 分类名称
		Class     string                `gorm:"column:class"`              // 分类标识
		Sort      int64                 `gorm:"column:sort"`               // 排序
		IsEnabled int64                 `gorm:"default:1"`                 // 是否有效 0无效 1有效
		IsDeleted soft_delete.DeletedAt `gorm:"softDelete:flag,default:0"` // 是否删除
		CreatedAt int64                 `gorm:"<-:create;autoCreateTime"`
		UpdatedAt int64                 `gorm:"<-;autoUpdateTime"` // 更新时间

		Children []Category `gorm:"foreignKey:ParentId;references:Id"`
	}
)

func (Category) TableName() string {
	return "`category`"
}

func newCategoryModel(conn *gorm.DB) *defaultCategoryModel {
	return &defaultCategoryModel{
		conn:  conn,
		table: "`category`",
	}
}

func (m *defaultCategoryModel) Insert(ctx context.Context, data *Category) error {
	err := m.conn.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultCategoryModel) FindOne(ctx context.Context, id int64) (*Category, error) {
	var resp Category
	err := m.conn.WithContext(ctx).Model(&Category{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) FindOneByClass(ctx context.Context, class string) (*Category, error) {
	var resp Category
	err := m.conn.WithContext(ctx).Model(&Category{}).Where("`class` = ?", class).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) Update(ctx context.Context, data *Category) error {
	err := m.conn.WithContext(ctx).Omit("is_enabled").Save(data).Error
	return err
}

func (m *defaultCategoryModel) Delete(ctx context.Context, id int64) error {
	err := m.conn.WithContext(ctx).Delete(&Category{}, id).Error

	return err
}

func (m *defaultCategoryModel) FindAll(ctx context.Context) ([]*Category, error) {
	var resp []*Category
	db := m.conn.WithContext(ctx).Model(&Category{})
	db.Order("sort ASC, created_at DESC")
	err := db.Find(&resp).Error
	if err != nil {
		return nil, err
	}
	return resp, nil

}

func (m *defaultCategoryModel) FindListByClass(ctx context.Context, class string) ([]*Category, error) {
	var resp []*Category
	db := m.conn.WithContext(ctx).Model(&Category{})
	db.Where("class = ?", class)
	db.Order("sort ASC, created_at DESC")
	err := db.Find(&resp).Error
	if err != nil {
		return nil, err
	}
	return resp, nil

}
func (m *defaultCategoryModel) FindListByPid(ctx context.Context, pid int64) ([]*Category, error) {
	var resp []*Category
	db := m.conn.WithContext(ctx).Model(&Category{})
	db.Where("parent_id = ?", pid)
	db.Order("sort ASC, created_at DESC")
	db.Preload("Children", "is_deleted = 0")
	err := db.Find(&resp).Error
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultCategoryModel) UpdateStatus(ctx context.Context, id int64) error {
	old, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}
	data := 0
	if old.IsEnabled == 0 {
		data = 1
	}

	err = m.conn.Model(&Category{}).Where("id = ?", id).Update("is_enabled", data).Error
	return err
}

func (m *defaultCategoryModel) tableName() string {
	return m.table
}
