// Code generated by goctl. DO NOT EDIT!

package model

import (
	"bodhiadmin/common/utils"
	"context"
	"github.com/SpectatorNan/gorm-zero/gormc"
	"gorm.io/gorm"
	"gorm.io/plugin/soft_delete"
	"strings"
)

var ()

type (
	mediaModel interface {
		Insert(ctx context.Context, data *Media) error
		FindOne(ctx context.Context, id int64) (*Media, error)
		Update(ctx context.Context, data *Media) error
		Delete(ctx context.Context, id int64) error

		FindListByPage(ctx context.Context, req PageReq) ([]*Media, int64, error)
		UpdateTitle(ctx context.Context, id int64, title string) error
	}

	defaultMediaModel struct {
		conn  *gorm.DB
		table string
	}

	Media struct {
		Id        int64                 `gorm:"column:id"`
		Title     string                `gorm:"column:title"`              // 文件标题
		Filename  string                `gorm:"column:filename"`           // 文件名
		Path      string                `gorm:"column:path"`               // 路径
		Type      string                `gorm:"column:type"`               // 类型
		Size      int64                 `gorm:"column:size"`               // 文件大小
		Meta      string                `gorm:"serializer:json"`           // 属性
		IsDeleted soft_delete.DeletedAt `gorm:"softDelete:flag,default:0"` // 是否删除
		CreatedAt int64                 `gorm:"<-:create;autoCreateTime"`
		UpdatedAt int64                 `gorm:"<-;autoUpdateTime"` // 更新时间
	}
)

func (Media) TableName() string {
	return "`media`"
}

func newMediaModel(conn *gorm.DB) *defaultMediaModel {
	return &defaultMediaModel{
		conn:  conn,
		table: "`media`",
	}
}

func (m *defaultMediaModel) Insert(ctx context.Context, data *Media) error {
	err := m.conn.WithContext(ctx).Save(&data).Error
	return err
}

func (m *defaultMediaModel) FindOne(ctx context.Context, id int64) (*Media, error) {
	var resp Media
	err := m.conn.WithContext(ctx).Model(&Media{}).Where("`id` = ?", id).Take(&resp).Error
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaModel) Update(ctx context.Context, data *Media) error {
	err := m.conn.WithContext(ctx).Omit("is_enabled").Save(data).Error
	return err
}
func (m *defaultMediaModel) UpdateTitle(ctx context.Context, id int64, title string) error {

	db := m.conn.WithContext(ctx).Model(Media{})
	err := db.Where("id = ?", id).Update("title", strings.TrimSpace(title)).Error
	return err
}

func (m *defaultMediaModel) Delete(ctx context.Context, id int64) error {
	err := m.conn.WithContext(ctx).Delete(&Media{}, id).Error

	return err
}
func (m *defaultMediaModel) FindListByPage(ctx context.Context, req PageReq) ([]*Media, int64, error) {
	var list []*Media
	var total int64

	sortBy := utils.GetSortByStr(req.Sort, req.Order, Media{})
	value := strings.TrimSpace(req.Value)
	db := m.conn.WithContext(ctx).Model(Media{})
	if len(req.Field) == 0 && len(value) != 0 {
		db.Where("`title` LIKE ? OR `filename` LIKE ?", value, value)
	}
	db.Count(&total)
	db.Scopes(utils.Paginate(req.Page, req.Size))
	db.Order(sortBy)
	err := db.Find(&list).Error

	if err != nil {
		return nil, 0, nil
	}
	return list, total, nil
}

func (m *defaultMediaModel) tableName() string {
	return m.table
}
