// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/article"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type ArticleServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedArticleServer
}

func NewArticleServer(svcCtx *svc.ServiceContext) *ArticleServer {
	return &ArticleServer{
		svcCtx: svcCtx,
	}
}

func (s *ArticleServer) InsertArticle(ctx context.Context, in *admin.ArticleUnit) (*admin.AffectedResp, error) {
	l := articlelogic.NewInsertArticleLogic(ctx, s.svcCtx)
	return l.InsertArticle(in)
}

func (s *ArticleServer) UpdateArticle(ctx context.Context, in *admin.ArticleUnit) (*admin.AffectedResp, error) {
	l := articlelogic.NewUpdateArticleLogic(ctx, s.svcCtx)
	return l.UpdateArticle(in)
}

func (s *ArticleServer) UpdateStatus(ctx context.Context, in *admin.StatusReq) (*admin.AffectedResp, error) {
	l := articlelogic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}

func (s *ArticleServer) RemoveArticle(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := articlelogic.NewRemoveArticleLogic(ctx, s.svcCtx)
	return l.RemoveArticle(in)
}

func (s *ArticleServer) GetArticle(ctx context.Context, in *admin.Id) (*admin.ArticleUnit, error) {
	l := articlelogic.NewGetArticleLogic(ctx, s.svcCtx)
	return l.GetArticle(in)
}

func (s *ArticleServer) ListArticle(ctx context.Context, in *admin.PageReq) (*admin.ListArticleResp, error) {
	l := articlelogic.NewListArticleLogic(ctx, s.svcCtx)
	return l.ListArticle(in)
}
