// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package node

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	BatchIdsReq       = admin.BatchIdsReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Node interface {
		InsertNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*AffectedResp, error)
		UpdateStatus(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		RemoveNode(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error)
		GetNode(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeUnit, error)
		GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeListResp, error)
		GetNodeListByGid(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeListResp, error)
		ListNode(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListNodeResp, error)
		BatchMove(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*AffectedResp, error)
		BatchRemove(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*AffectedResp, error)
	}

	defaultNode struct {
		cli zrpc.Client
	}
)

func NewNode(cli zrpc.Client) Node {
	return &defaultNode{
		cli: cli,
	}
}

func (m *defaultNode) InsertNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.InsertNode(ctx, in, opts...)
}

func (m *defaultNode) UpdateNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.UpdateNode(ctx, in, opts...)
}

func (m *defaultNode) UpdateStatus(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.UpdateStatus(ctx, in, opts...)
}

func (m *defaultNode) RemoveNode(ctx context.Context, in *Id, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.RemoveNode(ctx, in, opts...)
}

func (m *defaultNode) GetNode(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeUnit, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.GetNode(ctx, in, opts...)
}

func (m *defaultNode) GetList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeListResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.GetList(ctx, in, opts...)
}

func (m *defaultNode) GetNodeListByGid(ctx context.Context, in *Id, opts ...grpc.CallOption) (*NodeListResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.GetNodeListByGid(ctx, in, opts...)
}

func (m *defaultNode) ListNode(ctx context.Context, in *PageReq, opts ...grpc.CallOption) (*ListNodeResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.ListNode(ctx, in, opts...)
}

func (m *defaultNode) BatchMove(ctx context.Context, in *MoveReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.BatchMove(ctx, in, opts...)
}

func (m *defaultNode) BatchRemove(ctx context.Context, in *BatchIdsReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewNodeClient(m.cli.Conn())
	return client.BatchRemove(ctx, in, opts...)
}
