// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/nodegroup"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type NodeGroupServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedNodeGroupServer
}

func NewNodeGroupServer(svcCtx *svc.ServiceContext) *NodeGroupServer {
	return &NodeGroupServer{
		svcCtx: svcCtx,
	}
}

func (s *NodeGroupServer) InsertNodeGroup(ctx context.Context, in *admin.NodeGroupReq) (*admin.AffectedResp, error) {
	l := nodegrouplogic.NewInsertNodeGroupLogic(ctx, s.svcCtx)
	return l.InsertNodeGroup(in)
}

func (s *NodeGroupServer) UpdateNodeGroup(ctx context.Context, in *admin.NodeGroupReq) (*admin.AffectedResp, error) {
	l := nodegrouplogic.NewUpdateNodeGroupLogic(ctx, s.svcCtx)
	return l.UpdateNodeGroup(in)
}

func (s *NodeGroupServer) RemoveNodeGroup(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := nodegrouplogic.NewRemoveNodeGroupLogic(ctx, s.svcCtx)
	return l.RemoveNodeGroup(in)
}

func (s *NodeGroupServer) GetNodeGroup(ctx context.Context, in *admin.Id) (*admin.NodeGroupUnit, error) {
	l := nodegrouplogic.NewGetNodeGroupLogic(ctx, s.svcCtx)
	return l.GetNodeGroup(in)
}

func (s *NodeGroupServer) GetNodeGroupList(ctx context.Context, in *admin.Empty) (*admin.NodeGroupList, error) {
	l := nodegrouplogic.NewGetNodeGroupListLogic(ctx, s.svcCtx)
	return l.GetNodeGroupList(in)
}
