// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: admin.proto

package account

import (
	"context"

	"bodhiadmin/app/admin/rpc/proto/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AffectedResp      = admin.AffectedResp
	BatchIdsReq       = admin.BatchIdsReq
	Empty             = admin.Empty
	Id                = admin.Id
	ListMenuReq       = admin.ListMenuReq
	ListNodeResp      = admin.ListNodeResp
	ListRoleResp      = admin.ListRoleResp
	ListUserResp      = admin.ListUserResp
	LoginReq          = admin.LoginReq
	LoginResp         = admin.LoginResp
	MenuListResp      = admin.MenuListResp
	MenuReq           = admin.MenuReq
	MenuResp          = admin.MenuResp
	MenuTypeResp      = admin.MenuTypeResp
	MenuUnit          = admin.MenuUnit
	MoveReq           = admin.MoveReq
	NewUserReq        = admin.NewUserReq
	NodeGroupList     = admin.NodeGroupList
	NodeGroupReq      = admin.NodeGroupReq
	NodeGroupUnit     = admin.NodeGroupUnit
	NodeListResp      = admin.NodeListResp
	NodeReq           = admin.NodeReq
	NodeUnit          = admin.NodeUnit
	PageReq           = admin.PageReq
	PasswordReq       = admin.PasswordReq
	PermissionResp    = admin.PermissionResp
	RegisterReq       = admin.RegisterReq
	RoleListResp      = admin.RoleListResp
	RoleReq           = admin.RoleReq
	RoleUnit          = admin.RoleUnit
	StatusReq         = admin.StatusReq
	TokenReq          = admin.TokenReq
	TokenResp         = admin.TokenResp
	TokenUnit         = admin.TokenUnit
	UpdateUserRoleReq = admin.UpdateUserRoleReq
	UserPasswordReq   = admin.UserPasswordReq
	UserReq           = admin.UserReq
	UserResp          = admin.UserResp
	UserRoleListResp  = admin.UserRoleListResp
	UserRoleReq       = admin.UserRoleReq
	UserRoleUnit      = admin.UserRoleUnit
	UserUnit          = admin.UserUnit
	Uuid              = admin.Uuid
	UuidStatusReq     = admin.UuidStatusReq

	Account interface {
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*AffectedResp, error)
		RefreshToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*TokenResp, error)
		SetPassword(ctx context.Context, in *PasswordReq, opts ...grpc.CallOption) (*AffectedResp, error)
		GetPermission(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*PermissionResp, error)
	}

	defaultAccount struct {
		cli zrpc.Client
	}
)

func NewAccount(cli zrpc.Client) Account {
	return &defaultAccount{
		cli: cli,
	}
}

func (m *defaultAccount) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := admin.NewAccountClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultAccount) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewAccountClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultAccount) RefreshToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*TokenResp, error) {
	client := admin.NewAccountClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

func (m *defaultAccount) SetPassword(ctx context.Context, in *PasswordReq, opts ...grpc.CallOption) (*AffectedResp, error) {
	client := admin.NewAccountClient(m.cli.Conn())
	return client.SetPassword(ctx, in, opts...)
}

func (m *defaultAccount) GetPermission(ctx context.Context, in *Uuid, opts ...grpc.CallOption) (*PermissionResp, error) {
	client := admin.NewAccountClient(m.cli.Conn())
	return client.GetPermission(ctx, in, opts...)
}
