// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"bodhiadmin/app/admin/rpc/internal/logic/menu"
	"bodhiadmin/app/admin/rpc/internal/svc"
	"bodhiadmin/app/admin/rpc/proto/admin"
)

type MenuServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedMenuServer
}

func NewMenuServer(svcCtx *svc.ServiceContext) *MenuServer {
	return &MenuServer{
		svcCtx: svcCtx,
	}
}

func (s *MenuServer) InsertMenu(ctx context.Context, in *admin.MenuReq) (*admin.AffectedResp, error) {
	l := menulogic.NewInsertMenuLogic(ctx, s.svcCtx)
	return l.InsertMenu(in)
}

func (s *MenuServer) UpdateMenu(ctx context.Context, in *admin.MenuReq) (*admin.AffectedResp, error) {
	l := menulogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *MenuServer) UpdateStatus(ctx context.Context, in *admin.StatusReq) (*admin.AffectedResp, error) {
	l := menulogic.NewUpdateStatusLogic(ctx, s.svcCtx)
	return l.UpdateStatus(in)
}

func (s *MenuServer) RemoveMenu(ctx context.Context, in *admin.Id) (*admin.AffectedResp, error) {
	l := menulogic.NewRemoveMenuLogic(ctx, s.svcCtx)
	return l.RemoveMenu(in)
}

func (s *MenuServer) GetMenu(ctx context.Context, in *admin.Id) (*admin.MenuResp, error) {
	l := menulogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

func (s *MenuServer) GetMenuListByPid(ctx context.Context, in *admin.ListMenuReq) (*admin.MenuListResp, error) {
	l := menulogic.NewGetMenuListByPidLogic(ctx, s.svcCtx)
	return l.GetMenuListByPid(in)
}

func (s *MenuServer) GetMenuListByType(ctx context.Context, in *admin.MenuTypeResp) (*admin.MenuListResp, error) {
	l := menulogic.NewGetMenuListByTypeLogic(ctx, s.svcCtx)
	return l.GetMenuListByType(in)
}
